version: "3.9"

services:

  expo:
    build:
      context: ./EscapeGamenextDoor
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./EscapeGamenextDoor:/app
      - /app/node_modules     # Permet à npm install de fonctionner sans conflit
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
